services:
  frontend:
    depends_on:
      - backend
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      # Frontend calls backend from the browser via host published port
      VITE_API_URL: http://localhost:5000
    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/package-lock.json
          action: rebuild
        - path: ./frontend
          target: /app
          action: sync

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      # Match backend .env and server.js
      MONGODB_URI: mongodb://54.169.9.199:27017/Numerical
      PORT: 5000 
    develop:
      watch:
        - path: ./backend/package.json
          action: rebuild
        - path: ./backend/package-lock.json
          action: rebuild
        - path: ./backend
          target: /app
          action: sync

  # One-off seeding job that uses the backend image
  # seed:
  #   build: ./backend
  #   environment:
  #     MONGODB_URI: mongodb://54.169.9.199:27017/Numerical
  #   command: npm run seed:all
  #   restart: "no"

  # db:
  #   image: mongo:latest
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - ./mongo-data:/data/db